package kerho.test;
// Generated by ComTest BEGIN
import kerho.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.14 12:42:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa45() throws SailoException {    // Jasenet: 45
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    assertEquals("From: Jasenet line: 49", 0, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 50", 1, jasenet.getLkm()); 
    jasenet.lisaa(aku2); assertEquals("From: Jasenet line: 51", 2, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 52", 3, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 53", aku1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 54", aku2, jasenet.anna(1)); 
    assertEquals("From: Jasenet line: 55", aku1, jasenet.anna(2)); 
    assertEquals("From: Jasenet line: 56", false, jasenet.anna(1) == aku1); 
    assertEquals("From: Jasenet line: 57", true, jasenet.anna(1) == aku2); 
    try {
    assertEquals("From: Jasenet line: 58", aku1, jasenet.anna(3)); 
    fail("Jasenet: 58 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 59", 4, jasenet.getLkm()); 
    jasenet.lisaa(aku1); assertEquals("From: Jasenet line: 60", 5, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa78 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaa78() throws SailoException,CloneNotSupportedException {    // Jasenet: 78
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    assertEquals("From: Jasenet line: 84", 0, jasenet.getLkm()); 
    jasenet.korvaaTaiLisaa(aku1); assertEquals("From: Jasenet line: 85", 1, jasenet.getLkm()); 
    jasenet.korvaaTaiLisaa(aku2); assertEquals("From: Jasenet line: 86", 2, jasenet.getLkm()); 
    Jasen aku3 = aku1.clone(); 
    aku3.aseta(3,"kkk"); 
    Iterator<Jasen> it = jasenet.iterator(); 
    assertEquals("From: Jasenet line: 90", true, it.next() == aku1); 
    jasenet.korvaaTaiLisaa(aku3); assertEquals("From: Jasenet line: 91", 2, jasenet.getLkm()); 
    it = jasenet.iterator(); 
    Jasen j0 = it.next(); 
    assertEquals("From: Jasenet line: 94", aku3, j0); 
    assertEquals("From: Jasenet line: 95", true, j0 == aku3); 
    assertEquals("From: Jasenet line: 96", false, j0 == aku1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista132 
   * @throws SailoException when error
   */
  @Test
  public void testPoista132() throws SailoException {    // Jasenet: 132
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(), aku3 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    jasenet.lisaa(aku1); jasenet.lisaa(aku2); jasenet.lisaa(aku3); 
    assertEquals("From: Jasenet line: 139", 1, jasenet.poista(id1+1)); 
    assertEquals("From: Jasenet line: 140", null, jasenet.annaId(id1+1)); assertEquals("From: Jasenet line: 140", 2, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 141", 1, jasenet.poista(id1)); assertEquals("From: Jasenet line: 141", 1, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 142", 0, jasenet.poista(id1+3)); assertEquals("From: Jasenet line: 142", 1, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testJasenetIterator301 
   * @throws SailoException when error
   */
  @Test
  public void testJasenetIterator301() throws SailoException {    // Jasenet: 301
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    jasenet.lisaa(aku1); 
    jasenet.lisaa(aku2); 
    jasenet.lisaa(aku1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Jasen jasen:jasenet) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+jasen.getTunnusNro()); 
    String tulos = " " + aku1.getTunnusNro() + " " + aku2.getTunnusNro() + " " + aku1.getTunnusNro(); 
    assertEquals("From: Jasenet line: 320", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Jasen>  i=jasenet.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Jasen jasen = i.next(); 
    ids.append(" "+jasen.getTunnusNro()); 
    }
    assertEquals("From: Jasenet line: 328", tulos, ids.toString()); 
    Iterator<Jasen>  i=jasenet.iterator(); 
    assertEquals("From: Jasenet line: 331", true, i.next() == aku1); 
    assertEquals("From: Jasenet line: 332", true, i.next() == aku2); 
    assertEquals("From: Jasenet line: 333", true, i.next() == aku1); 
    try {
    i.next(); 
    fail("Jasenet: 335 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi395 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi395() throws SailoException {    // Jasenet: 395
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); jasen1.parse("1|Ankka Aku|030201-115H|Paratiisitie 13|"); 
    Jasen jasen2 = new Jasen(); jasen2.parse("2|Ankka Tupu||030552-123B|"); 
    Jasen jasen3 = new Jasen(); jasen3.parse("3|Susi Sepe|121237-121V||131313|Perämetsä"); 
    Jasen jasen4 = new Jasen(); jasen4.parse("4|Ankka Iines|030245-115V|Ankkakuja 9"); 
    Jasen jasen5 = new Jasen(); jasen5.parse("5|Ankka Roope|091007-408U|Ankkakuja 12"); 
    jasenet.lisaa(jasen1); jasenet.lisaa(jasen2); jasenet.lisaa(jasen3); jasenet.lisaa(jasen4); jasenet.lisaa(jasen5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId425 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId425() throws SailoException {    // Jasenet: 425
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(), aku3 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    jasenet.lisaa(aku1); jasenet.lisaa(aku2); jasenet.lisaa(aku3); 
    assertEquals("From: Jasenet line: 432", true, jasenet.annaId(id1  ) == aku1); 
    assertEquals("From: Jasenet line: 433", true, jasenet.annaId(id1+1) == aku2); 
    assertEquals("From: Jasenet line: 434", true, jasenet.annaId(id1+2) == aku3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId449 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId449() throws SailoException {    // Jasenet: 449
    Jasenet jasenet = new Jasenet(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(), aku3 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    jasenet.lisaa(aku1); jasenet.lisaa(aku2); jasenet.lisaa(aku3); 
    assertEquals("From: Jasenet line: 456", 1, jasenet.etsiId(id1+1)); 
    assertEquals("From: Jasenet line: 457", 2, jasenet.etsiId(id1+2)); 
  } // Generated by ComTest END
}