package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 16:42:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testGetNimi53 */
  @Test
  public void testGetNimi53() {    // Jasen: 53
    Jasen aku = new Jasen(); 
    aku.vastaaAkuAnkka(); 
    { String _l_=aku.getNimi(),_r_="Ankka Aku .*"; if ( !_l_.matches(_r_) ) fail("From: Jasen line: 56" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta151 */
  @Test
  public void testAseta151() {    // Jasen: 151
    Jasen jasen = new Jasen(); 
    assertEquals("From: Jasen line: 153", null, jasen.aseta(1,"Ankka Aku")); 
    { String _l_=jasen.aseta(2,"kissa"),_r_="Hetu liian lyhyt"; if ( !_l_.matches(_r_) ) fail("From: Jasen line: 154" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
    assertEquals("From: Jasen line: 155", "Tarkistusmerkin kuuluisi olla C", jasen.aseta(2,"030201-1111")); 
    assertEquals("From: Jasen line: 156", null, jasen.aseta(2,"030201-111C")); 
    assertEquals("From: Jasen line: 157", "Liittymisvuosi väärin jono = \"kissa\"", jasen.aseta(11,"kissa")); 
    assertEquals("From: Jasen line: 158", null, jasen.aseta(9,"1940")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi264 */
  @Test
  public void testRekisteroi264() {    // Jasen: 264
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 266", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Jasen line: 272", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString297 */
  @Test
  public void testToString297() {    // Jasen: 297
    Jasen jasen = new Jasen(); 
    jasen.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Jasen line: 300", true, jasen.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse328 */
  @Test
  public void testParse328() {    // Jasen: 328
    Jasen jasen = new Jasen(); 
    jasen.parse("   3  |  Ankka Aku   | 030201-111C"); 
    assertEquals("From: Jasen line: 331", 3, jasen.getTunnusNro()); 
    assertEquals("From: Jasen line: 332", true, jasen.toString().startsWith("3|Ankka Aku|030201-111C|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    jasen.rekisteroi(); 
    int n = jasen.getTunnusNro(); 
    jasen.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    jasen.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Jasen line: 338", n+20+1, jasen.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone407 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone407() throws CloneNotSupportedException {    // Jasen: 407
    Jasen jasen = new Jasen(); 
    jasen.parse("   3  |  Ankka Aku   | 123"); 
    Jasen kopio = jasen.clone(); 
    Object olio = jasen.clone(); 
    assertEquals("From: Jasen line: 413", jasen.toString(), kopio.toString()); 
    jasen.parse("   4  |  Ankka Tupu   | 123"); 
    assertEquals("From: Jasen line: 415", false, kopio.toString().equals(jasen.toString())); 
    assertEquals("From: Jasen line: 416", true, olio instanceof Jasen); 
  } // Generated by ComTest END
}