package kerho.test;
// Generated by ComTest BEGIN
import kerho.SailoException;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 16:38:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KerhoTest {


  // Generated by ComTest BEGIN  // Kerho: 14
   private Kerho kerho; 
   private Jasen aku1; 
   private Jasen aku2; 
   private int jid1; 
   private int jid2; 
   private Valine valine21; 
   private Valine valine11; 
   private Valine valine22; 
   private Valine valine12; 
   private Valine valine23; 

  @Before
   public void alustaKerho() {
     kerho = new Kerho(); 
     aku1 = new Jasen(); aku1.vastaaAkuAnkka(); aku1.rekisteroi(); 
     aku2 = new Jasen(); aku2.vastaaAkuAnkka(); aku2.rekisteroi(); 
     jid1 = aku1.getTunnusNro(); 
     jid2 = aku2.getTunnusNro(); 
     valine21 = new Valine(jid2); valine21.vastaaValineSukset(jid2); 
     valine11 = new Valine(jid1); valine11.vastaaValineSukset(jid1); 
     valine22 = new Valine(jid2); valine22.vastaaValineSukset(jid2); 
     valine12 = new Valine(jid1); valine12.vastaaValineSukset(jid1); 
     valine23 = new Valine(jid2); valine23.vastaaValineSukset(jid2); 
     try {
     kerho.lisaa(aku1); 
     kerho.lisaa(aku2); 
     kerho.lisaa(valine21); 
     kerho.lisaa(valine11); 
     kerho.lisaa(valine22); 
     kerho.lisaa(valine12); 
     kerho.lisaa(valine23); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista74 
   * @throws Exception when error
   */
  @Test
  public void testPoista74() throws Exception {    // Kerho: 74
    alustaKerho(); 
    assertEquals("From: Kerho line: 77", 2, kerho.etsi("*",0).size()); 
    assertEquals("From: Kerho line: 78", 2, kerho.annaValineet(aku1).size()); 
    assertEquals("From: Kerho line: 79", 1, kerho.poista(aku1)); 
    assertEquals("From: Kerho line: 80", 1, kerho.etsi("*",0).size()); 
    assertEquals("From: Kerho line: 81", 0, kerho.annaValineet(aku1).size()); 
    assertEquals("From: Kerho line: 82", 3, kerho.annaValineet(aku2).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaValine97 
   * @throws Exception when error
   */
  @Test
  public void testPoistaValine97() throws Exception {    // Kerho: 97
    alustaKerho(); 
    assertEquals("From: Kerho line: 100", 2, kerho.annaValineet(aku1).size()); 
    kerho.poistaValine(valine11); 
    assertEquals("From: Kerho line: 102", 1, kerho.annaValineet(aku1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa115 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa115() throws SailoException {    // Kerho: 115
    Kerho kerho = new Kerho(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    assertEquals("From: Kerho line: 120", 0, kerho.getJasenia()); 
    kerho.lisaa(aku1); assertEquals("From: Kerho line: 121", 1, kerho.getJasenia()); 
    kerho.lisaa(aku2); assertEquals("From: Kerho line: 122", 2, kerho.getJasenia()); 
    kerho.lisaa(aku1); assertEquals("From: Kerho line: 123", 3, kerho.getJasenia()); 
    assertEquals("From: Kerho line: 124", 3, kerho.getJasenia()); 
    assertEquals("From: Kerho line: 125", aku1, kerho.annaJasen(0)); 
    assertEquals("From: Kerho line: 126", aku2, kerho.annaJasen(1)); 
    assertEquals("From: Kerho line: 127", aku1, kerho.annaJasen(2)); 
    try {
    assertEquals("From: Kerho line: 128", aku1, kerho.annaJasen(3)); 
    fail("Kerho: 128 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kerho.lisaa(aku1); assertEquals("From: Kerho line: 129", 4, kerho.getJasenia()); 
    kerho.lisaa(aku1); assertEquals("From: Kerho line: 130", 5, kerho.getJasenia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa145 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa145() throws SailoException {    // Kerho: 145
    alustaKerho(); 
    assertEquals("From: Kerho line: 148", 2, kerho.etsi("*",0).size()); 
    kerho.korvaaTaiLisaa(aku1); 
    assertEquals("From: Kerho line: 150", 2, kerho.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKokemukset204 */
  @Test
  public void testAnnaKokemukset204() {    // Kerho: 204
    Kerho kerho = new Kerho(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(), aku3 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    int id2 = aku2.getTunnusNro(); 
    Kokemus pitsi11 = new Kokemus(id1); kerho.lisaa(pitsi11); 
    Kokemus pitsi12 = new Kokemus(id1); kerho.lisaa(pitsi12); 
    Kokemus pitsi21 = new Kokemus(id2); kerho.lisaa(pitsi21); 
    Kokemus pitsi22 = new Kokemus(id2); kerho.lisaa(pitsi22); 
    Kokemus pitsi23 = new Kokemus(id2); kerho.lisaa(pitsi23); 
    List<Kokemus> loytyneet; 
    loytyneet = kerho.annaKokemukset(aku3); 
    assertEquals("From: Kerho line: 220", 0, loytyneet.size()); 
    loytyneet = kerho.annaKokemukset(aku1); 
    assertEquals("From: Kerho line: 222", 2, loytyneet.size()); 
    assertEquals("From: Kerho line: 223", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Kerho line: 224", true, loytyneet.get(1) == pitsi12); 
    loytyneet = kerho.annaKokemukset(aku2); 
    assertEquals("From: Kerho line: 226", 3, loytyneet.size()); 
    assertEquals("From: Kerho line: 227", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaValineet240 */
  @Test
  public void testAnnaValineet240() {    // Kerho: 240
    Kerho kerho = new Kerho(); 
    Jasen aku1 = new Jasen(), aku2 = new Jasen(), aku3 = new Jasen(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    int id2 = aku2.getTunnusNro(); 
    Valine valine11 = new Valine(id1); kerho.lisaa(valine11); 
    Valine valine12 = new Valine(id1); kerho.lisaa(valine12); 
    Valine valine21 = new Valine(id2); kerho.lisaa(valine21); 
    Valine valine22 = new Valine(id2); kerho.lisaa(valine22); 
    Valine valine23 = new Valine(id2); kerho.lisaa(valine23); 
    List<Valine> loytyneet; 
    loytyneet = kerho.annaValineet(aku3); 
    assertEquals("From: Kerho line: 256", 0, loytyneet.size()); 
    loytyneet = kerho.annaValineet(aku1); 
    assertEquals("From: Kerho line: 258", 2, loytyneet.size()); 
    assertEquals("From: Kerho line: 259", true, loytyneet.get(0) == valine11); 
    assertEquals("From: Kerho line: 260", true, loytyneet.get(1) == valine12); 
    loytyneet = kerho.annaValineet(aku2); 
    assertEquals("From: Kerho line: 262", 3, loytyneet.size()); 
    assertEquals("From: Kerho line: 263", true, loytyneet.get(0) == valine21); 
  } // Generated by ComTest END
}