package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 15:26:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KokemusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi77 */
  @Test
  public void testRekisteroi77() {    // Kokemus: 77
    Kokemus pitsi1 = new Kokemus(); 
    assertEquals("From: Kokemus line: 79", 0, pitsi1.getTunnusNro()); 
    pitsi1.rekisteroi(); 
    Kokemus pitsi2 = new Kokemus(); 
    pitsi2.rekisteroi(); 
    int n1 = pitsi1.getTunnusNro(); 
    int n2 = pitsi2.getTunnusNro(); 
    assertEquals("From: Kokemus line: 85", n2-1, n1); 
  } // Generated by ComTest END
}