package kerho.test;
// Generated by ComTest BEGIN
import kerho.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 15:26:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KokemuksetTest {



  // Generated by ComTest BEGIN
  /** testIterator73 */
  @Test
  public void testIterator73() {    // Kokemukset: 73
    Kokemukset taitoTasot = new Kokemukset(); 
    Kokemus pitsi21 = new Kokemus(2); taitoTasot.lisaa(pitsi21); 
    Kokemus pitsi11 = new Kokemus(1); taitoTasot.lisaa(pitsi11); 
    Kokemus pitsi22 = new Kokemus(2); taitoTasot.lisaa(pitsi22); 
    Kokemus pitsi12 = new Kokemus(1); taitoTasot.lisaa(pitsi12); 
    Kokemus pitsi23 = new Kokemus(2); taitoTasot.lisaa(pitsi23); 
    Iterator<Kokemus> i2=taitoTasot.iterator(); 
    assertEquals("From: Kokemukset line: 85", pitsi21, i2.next()); 
    assertEquals("From: Kokemukset line: 86", pitsi11, i2.next()); 
    assertEquals("From: Kokemukset line: 87", pitsi22, i2.next()); 
    assertEquals("From: Kokemukset line: 88", pitsi12, i2.next()); 
    assertEquals("From: Kokemukset line: 89", pitsi23, i2.next()); 
    try {
    assertEquals("From: Kokemukset line: 90", pitsi12, i2.next()); 
    fail("Kokemukset: 90 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Kokemus har:taitoTasot ) {
    assertEquals("From: Kokemukset line: 96", jnrot[n], har.getJasenNro()); n++; 
    }
    assertEquals("From: Kokemukset line: 99", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKokemukset114 */
  @Test
  public void testAnnaKokemukset114() {    // Kokemukset: 114
    Kokemukset taitoTasot = new Kokemukset(); 
    Kokemus pitsi21 = new Kokemus(2); taitoTasot.lisaa(pitsi21); 
    Kokemus pitsi11 = new Kokemus(1); taitoTasot.lisaa(pitsi11); 
    Kokemus pitsi22 = new Kokemus(2); taitoTasot.lisaa(pitsi22); 
    Kokemus pitsi12 = new Kokemus(1); taitoTasot.lisaa(pitsi12); 
    Kokemus pitsi23 = new Kokemus(2); taitoTasot.lisaa(pitsi23); 
    Kokemus pitsi51 = new Kokemus(5); taitoTasot.lisaa(pitsi51); 
    List<Kokemus> loytyneet; 
    loytyneet = taitoTasot.annaKokemukset(3); 
    assertEquals("From: Kokemukset line: 127", 0, loytyneet.size()); 
    loytyneet = taitoTasot.annaKokemukset(1); 
    assertEquals("From: Kokemukset line: 129", 2, loytyneet.size()); 
    assertEquals("From: Kokemukset line: 130", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Kokemukset line: 131", true, loytyneet.get(1) == pitsi12); 
    loytyneet = taitoTasot.annaKokemukset(5); 
    assertEquals("From: Kokemukset line: 133", 1, loytyneet.size()); 
    assertEquals("From: Kokemukset line: 134", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}