package kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 15:26:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValineTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Valine: 86
    Kokemus pitsi1 = new Kokemus(); 
    assertEquals("From: Valine line: 88", 0, pitsi1.getTunnusNro()); 
    pitsi1.rekisteroi(); 
    Kokemus pitsi2 = new Kokemus(); 
    pitsi2.rekisteroi(); 
    int n1 = pitsi1.getTunnusNro(); 
    int n2 = pitsi2.getTunnusNro(); 
    assertEquals("From: Valine line: 94", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString127 */
  @Test
  public void testToString127() {    // Valine: 127
    Valine valine = new Valine(); 
    valine.parse("   2   |  sukset  | 1949 | kokenut "); 
    assertEquals("From: Valine line: 130", "2|sukset|1949|kokenut", valine.toString()); 
  } // Generated by ComTest END
}