package kerho.test;
// Generated by ComTest BEGIN
import java.io.File;
import kerho.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.13 16:56:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValineetTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista51 
   * @throws SailoException when error
   */
  @Test
  public void testPoista51() throws SailoException {    // Valineet: 51
    Valineet valineet = new Valineet(); 
    Valine valine21 = new Valine(); valine21.vastaaValineSukset(2); 
    Valine valine11 = new Valine(); valine11.vastaaValineSukset(1); 
    Valine valine22 = new Valine(); valine22.vastaaValineSukset(2); 
    Valine valine12 = new Valine(); valine12.vastaaValineSukset(1); 
    Valine valine23 = new Valine(); valine23.vastaaValineSukset(2); 
    valineet.lisaa(valine21); 
    valineet.lisaa(valine11); 
    valineet.lisaa(valine22); 
    valineet.lisaa(valine12); 
    assertEquals("From: Valineet line: 64", false, valineet.poista(valine23)); assertEquals("From: Valineet line: 64", 4, valineet.getLkm()); 
    assertEquals("From: Valineet line: 65", true, valineet.poista(valine11)); assertEquals("From: Valineet line: 65", 3, valineet.getLkm()); 
    List<Valine> h = valineet.annaValineet(1); 
    assertEquals("From: Valineet line: 67", 1, h.size()); 
    assertEquals("From: Valineet line: 68", valine12, h.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaJasenenValineet83 */
  @Test
  public void testPoistaJasenenValineet83() {    // Valineet: 83
    Valineet valineet = new Valineet(); 
    Valine valine21 = new Valine(); valine21.vastaaValineSukset(2); 
    Valine valine11 = new Valine(); valine11.vastaaValineSukset(1); 
    Valine valine22 = new Valine(); valine22.vastaaValineSukset(2); 
    Valine valine12 = new Valine(); valine12.vastaaValineSukset(1); 
    Valine valine23 = new Valine(); valine23.vastaaValineSukset(2); 
    valineet.lisaa(valine21); 
    valineet.lisaa(valine11); 
    valineet.lisaa(valine22); 
    valineet.lisaa(valine12); 
    valineet.lisaa(valine23); 
    assertEquals("From: Valineet line: 95", 3, valineet.poistaJasenenValineet(2)); assertEquals("From: Valineet line: 95", 2, valineet.getLkm()); 
    assertEquals("From: Valineet line: 96", 0, valineet.poistaJasenenValineet(3)); assertEquals("From: Valineet line: 96", 2, valineet.getLkm()); 
    List<Valine> h = valineet.annaValineet(2); 
    assertEquals("From: Valineet line: 98", 0, h.size()); 
    h = valineet.annaValineet(1); 
    assertEquals("From: Valineet line: 100", valine11, h.get(0)); 
    assertEquals("From: Valineet line: 101", valine12, h.get(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator167 */
  @Test
  public void testIterator167() {    // Valineet: 167
    Valineet valineet = new Valineet(); 
    Valine valine21 = new Valine(2); valineet.lisaa(valine21); 
    Valine valine11 = new Valine(1); valineet.lisaa(valine11); 
    Valine valine22 = new Valine(2); valineet.lisaa(valine22); 
    Valine valine12 = new Valine(1); valineet.lisaa(valine12); 
    Valine valine23 = new Valine(2); valineet.lisaa(valine23); 
    Iterator<Valine> i2=valineet.iterator(); 
    assertEquals("From: Valineet line: 179", valine21, i2.next()); 
    assertEquals("From: Valineet line: 180", valine11, i2.next()); 
    assertEquals("From: Valineet line: 181", valine22, i2.next()); 
    assertEquals("From: Valineet line: 182", valine12, i2.next()); 
    assertEquals("From: Valineet line: 183", valine23, i2.next()); 
    try {
    assertEquals("From: Valineet line: 184", valine12, i2.next()); 
    fail("Valineet: 184 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Valine val:valineet ) {
    assertEquals("From: Valineet line: 190", jnrot[n], val.getJasenNro()); n++; 
    }
    assertEquals("From: Valineet line: 193", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaValineet279 */
  @Test
  public void testAnnaValineet279() {    // Valineet: 279
    Valineet valineet = new Valineet(); 
    Valine valine21 = new Valine(2); valineet.lisaa(valine21); 
    Valine valine11 = new Valine(1); valineet.lisaa(valine11); 
    Valine valine22 = new Valine(2); valineet.lisaa(valine22); 
    Valine valine12 = new Valine(1); valineet.lisaa(valine12); 
    Valine valine23 = new Valine(2); valineet.lisaa(valine23); 
    Valine valine51 = new Valine(5); valineet.lisaa(valine51); 
    List<Valine> loytyneet; 
    loytyneet = valineet.annaValineet(3); 
    assertEquals("From: Valineet line: 292", 0, loytyneet.size()); 
    loytyneet = valineet.annaValineet(1); 
    assertEquals("From: Valineet line: 294", 2, loytyneet.size()); 
    assertEquals("From: Valineet line: 295", true, loytyneet.get(0) == valine11); 
    assertEquals("From: Valineet line: 296", true, loytyneet.get(1) == valine12); 
    loytyneet = valineet.annaValineet(5); 
    assertEquals("From: Valineet line: 298", 1, loytyneet.size()); 
    assertEquals("From: Valineet line: 299", true, loytyneet.get(0) == valine51); 
  } // Generated by ComTest END
}